### ISSUE TITLE
Plugin in kotlin environment

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#47]
Hi,

I'm experimenting with Android Studio 3.X and Kotlin. I've also converted some Java code which used an API generated by this plugin from a discovery document. However, after conversion the imports are not resolved anymore in the Kotlin code. Any ideas?

**Comment by loosebazooka** [comment]
Oh huh, I'm not really sure. If you haven't already, can you check if resolution is happening in the Java code? There have been instances in the past when a dependency resolution bug in preview versions of Android Studio manifests itself in this manner.

**Comment by Burtan** [comment]
I'm using the gradlew command in the terminal, so this shouldn't be affected by AS. My Java branch is building just fine. In the kotlin branch the build folder also contains the endpointsClientLibs but it does not seem to be recognized correctly.
The gradle file for both branches is the same except for the kotlin dependencies

**Comment by loosebazooka** [comment]
I'm having trouble visualizing this. Can you provide a small sample or something.

**Comment by Burtan** [comment]
I've created a small Android project. It has an Android module and a java module containing the endpoints API generated from a discovery file, which I've taken from the echo sample.
https://github.com/Burtan/EndpointsV2KotlinTest

**Comment by Burtan** [comment]
The problem remains with AS3.0-beta1

**Comment by loosebazooka** [comment]
Haven't had a chance to look at this yet, but thanks for the sample, I'll check it out today.

**Comment by loosebazooka** [comment]
I think I figured it out. We're really just designed to work with Java applications and the Kotlin plugin and Endpoints plugin were having some friendship issues. 
1. So `compileKotlin` was happening before the endpoints client library source was generated, this can be fixed by adding a simple `dependsOn` on all compile tasks instead of just the `compileJava` task as we have now : https://github.com/GoogleCloudPlatform/endpoints-framework-gradle-plugin/blob/master/src/main/java/com/google/cloud/tools/gradle/endpoints/framework/client/EndpointsClientPlugin.java#L220
2. Even after adding a `dependsOn`, the kotlin plugin is resolving the Java sourceSets before we modify them to add in our special generated source, so I have to move that code around presumably outside the afterEvaluate block : https://github.com/GoogleCloudPlatform/endpoints-framework-gradle-plugin/blob/master/src/main/java/com/google/cloud/tools/gradle/endpoints/framework/client/EndpointsClientPlugin.java#L224

**Comment by loosebazooka** [comment]
This will be in the next release.

**Comment by Burtan** [comment]
I see 1.0.1 is released since 3 days, but not on maven yet. Did you forget it? It was usually online very fast, that's why I ask.

**Comment by loosebazooka** [comment]
The release PR is still pending, I haven't pushed to maven central yet. I'll see if I can get it out today or tomorrow.
